using System.Reflection;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("INVENIO")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("INVENIO")]
[assembly: AssemblyProduct("INVENIO Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © INVENIO 2018")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("INVENIO.js.sys._System.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.bootstrap.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.jquery-2.2.4.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.jquery.mobile-1.4.6.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.unicode.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-odp.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.touch-edit.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.touch-scroll.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-resources.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-resources.min.en_US.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.culture.en-US.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-extensions.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.touch.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.touch-charts.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-menu.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.MicrosoftAjax.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.MicrosoftAjaxWebForms.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.sys.AjaxControlToolkit.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.js.daf.daf-membership.min.js", "text/javascript")]
[assembly: WebResource("INVENIO.Theme.DarkKnight.css", "text/css", PerformSubstitution=true)]
